### PR TITLE
allow service account annotations

### PR DESCRIPTION
**Pull request by andriisoldatenko**
fix https://github.com/astronomer/issues/issues/851

### CODE REVIEW

**Comment by ashb** [comment]
The fix asked about pods, this is adding it to service accounts... was this discussed please in the issue?

**Comment by andriisoldatenko** [comment]
@ashb yeah we need to add annotations to serviceaccounts:
https://github.com/astronomer/issues/issues/851#issuecomment-624282487

**Comment by schnie** [comment]
Yea, we'll need to refactor to add support for the webserver and dynamic pods as well.

@andriisoldatenko do we want to merge this and do that in a separate PR or do you want to add to this one? Looks fine to me as we have it now.

**Comment by andriisoldatenko** [comment]
@schnie @ashb based on this document https://github.com/astronomer/docs/blob/master/v0.10/aws-iam-roles.md#iam-roles
do we need to annotate pods too with same role?

**Comment by schnie** [comment]
> @schnie @ashb based on this document https://github.com/astronomer/docs/blob/master/v0.10/aws-iam-roles.md#iam-roles
> do we need to annotate pods too with same role?

I think just the service account. That example is manually annotating the worker service account.

**Comment by andriisoldatenko** [comment]
@schnie cool! Let me know if i need to add any code to this PR.

**Comment by schnie** [comment]
@andriisoldatenko we need to add a service account for the webserver too. Also what service account do kubernetes pod operators run under?

I assume Celery and Kubernetes Executor pods all run under the worker account we have now?

**Comment by andriisoldatenko** [comment]
@schnie AFAIK yes
```
grep -R "worker-serviceaccount" -A2 -B2 .
./templates/rbac/pod-launcher-rolebinding.yaml-{{- if $grantWorker }}
./templates/rbac/pod-launcher-rolebinding.yaml-  - kind: ServiceAccount
./templates/rbac/pod-launcher-rolebinding.yaml:    name: {{ .Release.Name }}-worker-serviceaccount
./templates/rbac/pod-launcher-rolebinding.yaml-    namespace: {{ .Release.Namespace }}
./templates/rbac/pod-launcher-rolebinding.yaml-{{- end }}
--
--
./templates/workers/worker-deployment.yaml-      terminationGracePeriodSeconds: {{ .Values.workers.terminationGracePeriodSeconds }}
./templates/workers/worker-deployment.yaml-      restartPolicy: Always
./templates/workers/worker-deployment.yaml:      serviceAccountName: {{ .Release.Name }}-worker-serviceaccount
./templates/workers/worker-deployment.yaml-      securityContext:
./templates/workers/worker-deployment.yaml-        runAsUser: {{ .Values.uid }}
--
--
./templates/workers/worker-serviceaccount.yaml-apiVersion: v1
./templates/workers/worker-serviceaccount.yaml-metadata:
./templates/workers/worker-serviceaccount.yaml:  name: {{ .Release.Name }}-worker-serviceaccount
./templates/workers/worker-serviceaccount.yaml-  annotations:
./templates/workers/worker-serviceaccount.yaml-    {{- if .Values.serviceAccountAnnotations }}
--
--
./templates/configmap.yaml-    worker_container_tag = {{ .Values.images.airflow.tag }}
./templates/configmap.yaml-    worker_container_image_pull_policy = {{ .Values.images.airflow.pullPolicy }}
./templates/configmap.yaml:    worker_service_account_name = {{ .Release.Name }}-worker-serviceaccount
./templates/configmap.yaml-    image_pull_secrets = {{ template "registry_secret" . }}
./templates/configmap.yaml-    dags_in_image = True
```

**Comment by andriisoldatenko** [comment]
@schnie @ashb 
i did some practical tests:
logs from houston-api
```
executor: LocalExecutor
serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: andrii-role

2020-05-13T22:26:48 INFO Calling commander method #createDeployment
2020-05-13T22:26:50 INFO Response from #createDeployment: {"result":{"success":true,"message":"Deployment Created"},"deployment":{"releaseName":"astral-umbra-2405"}}
2020-05-13T22:26:50 DEBUG ::ffff:10.244.0.11 - POST /v1 HTTP/1.1 200 370 - 2358.793 ms
2020-05-13T22:26:53 DEBUG ::ffff:10.244.0.1 - GET /v1/healthz HTTP/1.1 200 2 - 0.374 ms
2020-05-13T22:26:56 DEBUG ::ffff:10.244.0.1 - GET /v1/healthz HTTP/1.1 200 2 - 0.300 ms
```

```
kubectl get serviceaccounts earthbound-photon-6643-scheduler-serviceaccount -n astronomer-earthbound-photon-6643 -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: test
  creationTimestamp: "2020-05-14T15:50:32Z"
```

**Comment by schnie** [comment]
@vparekh94 what do you think here? Are we ok to have all of a deployments Airflow pods running under the same IAM role or do people need to separate out?

My gut says that as long as we include these same annotations for the webserver (incoming commit), we'll have enough to fit the initial use-case.

I could defiantly see the use-case for separate roles, but not sure if we have anyone who'd utilize that now. We'd also have to think about a different UX for that. I could see maybe assigning different IAM roles to different KEDA queues or something in the future.

**Comment by vparekh94** [comment]
I think for the first iteration of this and for our contractual commit, having the same annotations on all pods of a deployment (as long as you can add different annotations to different deployments) is perfect. 

Anything more, I think that @schnie is right on the money- different annotations on different pods could potentially be a feature people want in the future, but for now, they can just spin up different airflow instances when they need certain jobs to have different roles.

**Comment by andriisoldatenko** [comment]
@schnie done.

**Pull request merged**
