### PR TITLE
Add redirect old style uri to new style for airflow api too

### PR DESCRIPTION
**Pull request by andriisoldatenko**
fix https://github.com/astronomer/issues/issues/957

### CODE REVIEW

**Comment by ashb** [comment]
Cc @dImberman you'll need to update the annotations in your pr

**Comment by andriisoldatenko** [comment]
practically LGTM:
```
curl -L -X POST 'https://optical-thermal-0159-airflow.staging.astronomer.io/api/experimental/dags/example_dag/dag_runs' -d '{"conf":"{\"key\":\"value\"}"}' -H 'cookie: astronomer_staging_astronomer_io_auth=<token>' --compressed

{"message":"Created <DagRun example_dag @ 2020-03-12 19:02:50+00:00: manual__2020-03-12T19:02:50+00:00, externally triggered: True>"}
```

**Comment by andriisoldatenko** [comment]
```
```

**Comment by dimberman** [comment]
@andriisoldatenko @schnie do we not need a similar fix for flower?

**Comment by ashb** [comment]
It's less urgent for flower as it's mostly used via a browser, and is mostly GET requests too.

But we probably should while we're here, yes

**Comment by andriisoldatenko** [comment]
@dimberman do you mean https://flower.readthedocs.io/en/latest/api.html right?

**Pull request merged**
