### PR TITLE
version 1.7.2

### PR DESCRIPTION
**Pull request by pgvishnuram**
## Description

* 1.7.1 -> 1.7.2

## Related Issues

NA - This is an new patch version release to include gitsync relay features

## Testing

NA

## Merging

merge to release-1.7 branch.

### CODE REVIEW

**Review by danielhoherd — APPROVED** [review]

**Comment by vishwas-astro** [comment]
@danielhoherd has this been cherry picked to release-1.7 branch and 1.7.2 of airflow helm chart released?

Also are we now using the official OSS 1.7.0 release in our helm chart? OR are we still using our forked version of it?

**Comment by danielhoherd** [comment]
@vishwas-astro yes, I had to resolve some conflicts due to branch divergence, then I merged master into release-1.7 branch.

**Comment by vishwas-astro** [comment]
@danielhoherd looks like we are still using the Astro version of the OSS chart - https://github.com/astronomer/airflow-chart/blob/master/Chart.yaml#L12. Can we not switch to the official 1.7.0 OSS chart at this time? cc: @pgvishnuram @rishkarajgi @jedcunningham

**Comment by danielhoherd** [comment]
I would love to get back onto the OSS one.

**Comment by vishwas-astro** [comment]
@danielhoherd - https://astronomer.slack.com/archives/CEPE4K68P/p1668540992104539?thread_ts=1667242450.075269&cid=CEPE4K68P

**Pull request merged**
