### PR TITLE
update nginx worker connections and nginx worker process

### PR DESCRIPTION
**Pull request by pgvishnuram**
## Description

This PR fixes an issue where on baremetal installation worker process causing an OOM.

what is worker process ?
worker process that handles the incoming request
setting auto automatically adjust the number of Nginx worker processes based on available cores

what is worker connections ?
maximum number of simultaneous connections that can be opened by a worker process.

## Related Issues

- https://github.com/astronomer/issues/issues/6685

## Testing

QA should validate the values in nginx config when auth sidecar is enabled

## Merging

cherry-pick to all valid releases

### CODE REVIEW

**Comment by pgvishnuram** [comment]
@danielhoherd @rob-1126 should we expose this as a user configurable option or let us hardcode to defaults

**Review by rujhan-arora-astronomer — COMMENTED** [review]
Why did we chose 1 and 3072 specifically? @pgvishnuram Why not some other numbers?

**Comment by pgvishnuram** [comment]
> Why did we chose 1 and 3072 specifically? @pgvishnuram Why not some other numbers?

1 is defaut and 3072 is 6 times the defaukt

**Review by danielhoherd — APPROVED** [review]
I have no idea if these numbers are wise, but they look like they won't break the code, so LGTM.

**Pull request merged**
