### PR TITLE
Fix typo of resultBackendConnection

### PR DESCRIPTION
**Pull request by vsimon**

### CODE REVIEW

**Comment by vsimon** [comment]
I just saw the apache/airflow chart so should everything be merged into there instead and cease here? 

This chart can be installed via a "repo" and that other one seems to install only from source? Until it is publish-ready, what is the recommended route to take?

**Comment by schnie** [comment]
Hey @vsimon I'd probably recommend installing the apache version from source. It is a little bit more friendly to the community needs, as opposed to the Astronomer needs.

In addition to getting the community to converge on a single Kube deployment, this chart was getting pulled in too many directions, so splitting it out should let them evolve quicker.

Ideally we can get the apache version published somewhere soon.

**Comment by vsimon** [comment]
OK, thanks @schnie 

I put this up there too https://github.com/apache/airflow/pull/9537

**Comment by schnie** [comment]
Thanks!

**Pull request merged**
