### PR TITLE
Fixing the init container config error with no secret file found

### PR DESCRIPTION
**Pull request by kushalmalani**
## Description

> Describe the purpose of this pull request.
Fixing the init container config error with no secret file found

## PR Title

> Please make the PR title informative to the user experience. For example when adding a feature, say "Add metrics tab for Deployments" instead of "Bump Astro-UI to version X.Y.Z". Bugs are sometimes harder to make customer-facing because they are very detailed, but do what you can. Instead of "Fix metrics cardinality bug" (user does not know what 'cardinality' means and does not matter to them), say "Fix bug slowing down the metrics tab". The PR title will be used for the commit message when it's merged, and these commit messages are used to generate customer-facing release notes.

## 🎟 Issue(s)

Resolves astronomer/issues#XXXX

## 🧪  Testing

> What are the main risks associated with this change, and how are they addressed by tests added in this PR?

> Please add helm unit testing, if applicable. The docs are regretfully sparse for helm unit testing, [here](https://github.com/astronomer/helm-unittest/blob/main/DOCUMENT.md) is what we have to work with. In general, these kind of tests can be used for specific assertions like 'when these values are set, the resource ends up looking like XYZ' but not for generalized assertions like 'for all resources, make sure the namespace is not set to the release name'.

> Please also add to the system testing [here](../tests/functional-tests). This kind of testing allows you to connect into any live, running pod to make assertions about how they are operating.

## 📸 Screenshots

> Add screenshots to illustrate the changes, if applicable.

## 📋 Checklist

- [ ] The PR title is informative to the user experience
- [ ] Functional test(s) added
- [ ] Helm chart unit test(s)

### CODE REVIEW

**Review by sjmiller609 — CHANGES_REQUESTED** [review]
I think you need to account for the conditional https://github.com/astronomer/airflow-chart/blob/b37000e8737906ef6ba06fb4fa2ada6c0c8f7fff/templates/_helpers.yaml#L56

and also please complete the PR template.

**Comment by kushalmalani** [comment]
> I think you need to account for the conditional
> 
> https://github.com/astronomer/airflow-chart/blob/b37000e8737906ef6ba06fb4fa2ada6c0c8f7fff/templates/_helpers.yaml#L56
> 
> and also please complete the PR template.

@sjmiller609 Init containers do not need custom environment variables. I am just adding the standard custom environment variables helper

**Comment by sjmiller609** [comment]
I'm worried that this change might not address the problem. This feature is intended to make use of the all-at-once secret mount in order to avoid race conditions between the env var secret changing, and the deployment changing.

```
        envFrom:
        - secretRef:
            name: test-kube-env
```

Currently, this secret does not exist in the namespace in our test cluster
```
 $ k get secrets
NAME                                                       TYPE                                  DATA   AGE
astronomer-houston-jwt-signing-certificate                 Opaque                                1      19h
default-token-6xjrk                                        kubernetes.io/service-account-token   3      19h
sh.helm.release.v1.test-astrotest-2010.v1                  helm.sh/release.v1                    1      19h
test-astrotest-2010-airflow-metadata                       Opaque                                1      19h
test-astrotest-2010-airflow-result-backend                 Opaque                                1      19h
test-astrotest-2010-broker-url                             Opaque                                1      19h
test-astrotest-2010-cleanup-serviceaccount-token-kqp8t     kubernetes.io/service-account-token   3      19h
test-astrotest-2010-elasticsearch                          Opaque                                1      19h
test-astrotest-2010-fernet-key                             Opaque                                1      19h
test-astrotest-2010-pgbouncer-config                       Opaque                                2      19h
test-astrotest-2010-pgbouncer-stats                        Opaque                                1      19h
test-astrotest-2010-redis-password                         Opaque                                1      19h
test-astrotest-2010-registry                               kubernetes.io/dockerconfigjson        1      19h
test-astrotest-2010-scheduler-serviceaccount-token-jhwhk   kubernetes.io/service-account-token   3      19h
test-astrotest-2010-webserver-serviceaccount-token-4zphz   kubernetes.io/service-account-token   3      19h
test-astrotest-2010-worker-serviceaccount-token-znlk5      kubernetes.io/service-account-token   3      19h
```
and the airflow workloads are trying to consume it. I think this change does not address that issue.

**Comment by kushalmalani** [comment]
The reason for that file not being there is because the pods never left the init container phase to app container phase. I am not 100% confident of the behavior on upgrade-deployments, what exactly the flow is. But in theory, houston will ask commander to create and empty secret file.

I cant test this locally, since there is no way for astronomer/astronomer to pick local airflow charts.

**Pull request closed without merging**
